name: Build Vial Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout Vial-QMK
        run: |
          # Fix the "dubious ownership" error
          git config --global --add safe.directory /__w/klavye/klavye
          
          git clone https://github.com/vial-kb/vial-qmk.git .
          git submodule update --init --recursive

      - name: Checkout Your Keyboard Files
        uses: actions/checkout@v4
        with:
          path: my-config

      - name: Install ARM Toolchain
        run: |
          apt-get update
          apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Build Firmware
        run: |
          mkdir -p keyboards/handwired/edin
          cp -R my-config/keyboards/handwired/edin/* keyboards/handwired/edin/
          
          qmk compile -kb handwired/edin -km vial
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: handwired_edin_vial
          path: ./*.uf2