name: Build Vial Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM Toolchain
        run: |
          apt-get update
          apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Build Firmware
        run: |
          qmk setup -y
          # This line moves your folder so QMK can find it
          mkdir -p qmk_firmware/keyboards/handwired
          cp -R keyboards/handwired/edin qmk_firmware/keyboards/handwired/
          
          # Now run the compile command from inside the qmk_firmware folder
          cd qmk_firmware
          qmk compile -kb handwired/edin -km vial
          
          # Move the result back to the root so the 'upload' step can find it
          cp *.uf2 ..
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: handwired_edin_vial
          path: ./*.uf2